spring:
  application:
    name: auth-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:authdb
    username: sa
    password:


  security:
    oauth2:
        client:
          registration:
            google:
              client-name: google
              client-id:
              client-secret:
              redirect-uri: http://localhost:8080/login/oauth2/code/google
              authorization-grant-type: authorization_code
              scope:
                - profile
                - email
            naver:
              client-name: naver
              client-id:
              client-secret:
              redirect-uri: http://localhost:8080/login/oauth2/code/naver
              authorization-grant-type: authorization_code
              scope:
                - name
                - email
          provider:
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response

client:
  web:
    origin: http://localhost:8081
    successUrl: http://localhost:8081/

jwt:
  secret: 59fa5382544d33f918331b346e3906e6ad99f4b6fd29e07f7889b5369b82c02e0966cfafd4779d88f93f521d5e5aaee83e6438542075b751db6ddc2934345a0c
  accessTokenExpiration: 36000000
  refreshTokenExpiration: 604800000


