spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ddakta_db?currentSchema=auth
    username: ddakta_user
    password: ddakta_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: default-development-secret-key-please-change-in-production
  access-token-validity: 900000  # 15 minutes in milliseconds
  refresh-token-validity: 604800000  # 7 days in milliseconds

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    com.ddakta.auth: DEBUG
    org.springframework.security: DEBUG
