global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'test'
    
scrape_configs:
  # Matching Service instances
  - job_name: 'matching-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 
        - 'matching-service-1:8082'
        - 'matching-service-2:8083'
        labels:
          service: 'matching-service'
          
  # Redis exporter (if needed)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-test:6379']
        labels:
          service: 'redis'
          
  # Kafka exporter (if needed)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-test:9093']
        labels:
          service: 'kafka'
          
  # PostgreSQL exporter (if needed)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-test:5432']
        labels:
          service: 'postgresql'

# Alerting rules
rule_files:
  - '/etc/prometheus/alerts/*.yml'

# Alert manager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []