server:
  port: 8083

spring:
  application:
    name: location-service
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


app:
  ws:
    allowed-origins: ${WS_ALLOWED_ORIGINS:}
