server:
  port: 8080

spring:
  application.name: location-service
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

security:
  jwt:
    secret: ${JWT_SECRET:YourSuperSecretKey}

app:
  ws:
    allowed-origins: ${WS_ALLOWED_ORIGINS:}
