spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ddakta_matching_local
    username: ddakta
    password: ddakta123
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
  
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    enabled: false

feign:
  client:
    config:
      default:
        loggerLevel: FULL

ddakta:
  auth-service:
    url: http://localhost:8081
  location-service:
    url: http://localhost:8083
  payment-service:
    url: http://localhost:8084

logging:
  level:
    com.ddakta.matching: DEBUG
    org.springframework.statemachine: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE