server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: AUTH-SERVICE
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**
                -
            - id: MATCHING-SERVICE
              uri: lb://MATCHING-SERVICE
              predicates:
                - Path=/api/v1/driver-calls/**, /api/v1/rides/**, /api/v1/matching/**

            - id: LOCATION-SERVICE
              uri: lb://LOCATION-SERVICE
              predicates:
                - Path=/api/v1/locations/**
                -
            - id: PAYMENT-SERVICE
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/v1/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

