spring:
  application:
    name: dispatch-visualizer-service
  main:
    web-application-type: servlet

server:
  port: 8080

# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}

# Service URLs
location:
  service:
    ws:
      url: ws://localhost:8083/ws/locations

matching:
  service:
    api:
      url: http://localhost:8082

logging:
  level:
    com.ddakta: DEBUG
    org.springframework: INFO
